# Generated by Django 4.2 on 2023-04-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Posts',
            new_name='cats',
        ),
    ]
